# This job publishes a release on PyPI when a Git tag is pushed.
# See RELEASE.txt for further instructions.
name: Publish release on PyPI

on: push

jobs:
  publish-to-pypi:
    name: Publish release on PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/zbarlight
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install pypa/build
      run: pip install build
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libzbar-dev
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
